org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
fabric_loader_version=0.16.14
fabric_api_version=0.116.15+1.21.1
neo_version=21.1.248
neoform_version=1.21.1-20240808.144430
loom_version=1.11.7
moddev_version=2.0.143

mod_id=tempestfx
mod_name=Thunderhead
mod_author=GestSe
mod_version=1.3.0
mod_group=dev.tempestfx
mod_license=MIT
