package dev.tempestfx.lightning;

import dev.tempestfx.math.Bounds3d;
import dev.tempestfx.math.StrikeSeed;
import dev.tempestfx.math.Vec3d;
import java.util.ArrayList;
import java.util.List;

/**
 * Horizontal channels travelling through a storm rather than down out of it.
 *
 * <p>A cloud-to-cloud discharge is not a ground bolt turned on its side. It advances in long legs
 * that change heading and altitude at each joint, which is what produces the stepped horizontal
 * silhouette:
 *
 * <pre>
 *                ________
 *        _______/        \____
 *  _____/                    \____
 * </pre>
 *
 * <p>Each leg is generated by the same displacement strategy the ground bolts use - the channel
 * texture, the fork weighting and the width ladder are the parts that make a strand read as
 * lightning, and duplicating them here would mean maintaining two of them. What this class adds is
 * the route, the segment budget shared across it, and the remapping that makes the leader travel the
 * whole run end to end instead of restarting at every joint.
 */
public final class AerialChannelStrategy implements LightningGeometryStrategy {
    /** Fewest and most legs a channel is broken into. */
    private static final int MIN_LEGS = 2;
    private static final int MAX_LEGS = 6;
    /** How far a joint may wander off the straight line, as a fraction of the total span. */
    private static final double LATERAL_WANDER = 0.16;
    /** How far a joint may rise or fall, as a fraction of the total span. */
    private static final double VERTICAL_WANDER = 0.07;
    /** Salt for the leg-count draw, kept clear of every other sample of the same seed. */
    private static final long LEG_COUNT_SALT = 0x5eed1;
    /**
     * Blocks of channel each segment should span.
     *
     * <p>Subdivision has to follow the length of the leg it is applied to. A ground bolt spends
     * seven generations on its whole height; giving each of five legs seven generations of its own
     * chops a horizontal channel into segments a few tenths of a block long, and once a segment is
     * shorter than the ribbon drawn along it is wide, consecutive quads overlap at sharp angles
     * instead of joining - which is the torn look, not the channel one. Two blocks a segment matches
     * what a ground bolt of the tuned height produces.
     */
    private static final double TARGET_SEGMENT_BLOCKS = 2.0;

    private final LightningGeometryStrategy legStrategy;

    public AerialChannelStrategy() {
        this(new MidpointDisplacementStrategy());
    }

    public AerialChannelStrategy(LightningGeometryStrategy legStrategy) {
        this.legStrategy = legStrategy;
    }

    @Override
    public LightningGeometry generate(LightningBolt bolt) {
        Vec3d[] route = route(bolt);
        int legCount = route.length - 1;
        List<LightningBranch> branches = new ArrayList<>();
        Bounds3d bounds = Bounds3d.empty();
        int remaining = bolt.config().maxSegments();

        for (int leg = 0; leg < legCount; leg++) {
            if (remaining <= 32) break;
            int share = Math.max(32, remaining / (legCount - leg));
            LightningBolt legBolt = LightningBolt.builder()
                .start(route[leg])
                .end(route[leg + 1])
                .seed(StrikeSeed.derive(bolt.seed(), 0xc10d + leg))
                .intensity(bolt.intensity())
                .config(bolt.config()
                    .withGenerations(generationsFor(route[leg].distanceTo(route[leg + 1]),
                        bolt.config().generations()))
                    .withMaxSegments(share))
                .build();

            LightningGeometry legGeometry = legStrategy.generate(legBolt);
            int used = 0;
            for (LightningBranch branch : legGeometry.branches()) {
                List<LightningSegment> mapped = new ArrayList<>(branch.segments().size());
                for (LightningSegment segment : branch.segments()) {
                    mapped.add(reAlong(segment, leg, legCount));
                    bounds = bounds.include(segment.start()).include(segment.end());
                }
                used += mapped.size();
                branches.add(new LightningBranch(branch.depth(), branch.seed(), mapped));
            }
            remaining -= used;
        }
        return new LightningGeometry(branches, bounds, bolt.seed());
    }

    /**
     * Subdivisions for a leg of this length, so segment length stays roughly constant however long
     * the channel is and however many legs it was broken into.
     *
     * @param maximum the archetype's own generation count, which this never exceeds
     */
    static int generationsFor(double legLength, int maximum) {
        double segments = Math.max(2, legLength / TARGET_SEGMENT_BLOCKS);
        int wanted = (int) Math.round(Math.log(segments) / Math.log(2));
        return Math.max(3, Math.min(maximum, wanted));
    }

    /**
     * Places a segment on the whole run's timeline instead of its own leg's, so the leader crosses
     * the sky once rather than restarting at every joint.
     */
    private static LightningSegment reAlong(LightningSegment segment, int leg, int legCount) {
        double start = (leg + segment.alongStart()) / legCount;
        double end = Math.min(1, (leg + segment.alongEnd()) / legCount);
        return new LightningSegment(segment.start(), segment.end(), segment.branchDepth(),
            segment.startWidth(), segment.endWidth(), segment.intensity(),
            start, Math.max(start + 1.0e-4, end), segment.visibilityMask());
    }

    /** The joints the channel travels through, wandering off the direct line as it goes. */
    private static Vec3d[] route(LightningBolt bolt) {
        Vec3d start = bolt.start();
        Vec3d end = bolt.end();
        long seed = bolt.seed();
        int legs = MIN_LEGS + (int) (StrikeSeed.unit(seed, LEG_COUNT_SALT) * (MAX_LEGS - MIN_LEGS + 1));
        legs = Math.max(MIN_LEGS, Math.min(MAX_LEGS, legs));

        Vec3d span = end.subtract(start);
        double length = span.length();
        // The frame the wander happens in: one axis across the run, one vertical.
        Vec3d forward = length > 1.0e-6 ? span.scale(1 / length) : new Vec3d(1, 0, 0);
        Vec3d side = new Vec3d(-forward.z(), 0, forward.x());
        double sideLength = side.length();
        side = sideLength > 1.0e-6 ? side.scale(1 / sideLength) : new Vec3d(0, 0, 1);

        Vec3d[] route = new Vec3d[legs + 1];
        route[0] = start;
        route[legs] = end;
        for (int index = 1; index < legs; index++) {
            double t = index / (double) legs;
            // Wander tapers to nothing at both ends, so the channel still starts and finishes where
            // the planner asked it to.
            double taper = Math.sin(Math.PI * t);
            double lateral = StrikeSeed.signed(seed, 0x2000 + index) * length * LATERAL_WANDER * taper;
            double vertical = StrikeSeed.signed(seed, 0x3000 + index) * length * VERTICAL_WANDER * taper;
            route[index] = start.add(span.scale(t)).add(side.scale(lateral)).add(0, vertical, 0);
        }
        return route;
    }
}
